# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vedo_service_pb2 as vedo__service__pb2


class VedoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMeshPoints = channel.unary_unary(
                '/protos.Vedo/GetMeshPoints',
                request_serializer=vedo__service__pb2.GetMeshPointsRequest.SerializeToString,
                response_deserializer=vedo__service__pb2.GetMeshPointsResult.FromString,
                )


class VedoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMeshPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VedoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMeshPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeshPoints,
                    request_deserializer=vedo__service__pb2.GetMeshPointsRequest.FromString,
                    response_serializer=vedo__service__pb2.GetMeshPointsResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.Vedo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Vedo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMeshPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Vedo/GetMeshPoints',
            vedo__service__pb2.GetMeshPointsRequest.SerializeToString,
            vedo__service__pb2.GetMeshPointsResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
